//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickPerformanceCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPickPerformance
    {
        public string Symbol { get; set; }
        public System.DateTime PickDate { get; set; }
        public int PickType { get; set; }
        public Nullable<double> PrevBigVolumeRatio { get; set; }
        public Nullable<double> RatioVSHigh { get; set; }
        public Nullable<double> RatioVSLow { get; set; }
        public Nullable<double> M1Perf { get; set; }
        public Nullable<double> M3Perf { get; set; }
        public Nullable<double> M6Perf { get; set; }
        public Nullable<double> M12Perf { get; set; }
        public Nullable<double> M18Perf { get; set; }
    }
}
